import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        wine: "var(--color-wine)",
        "wine-deep": "var(--color-wine-deep)",
        ink: "var(--color-ink)",
        body: "var(--color-body)",
        muted: "var(--color-muted)",
        canvas: "var(--color-canvas)",
        surface: "var(--color-surface)",
        blush: "var(--color-blush)",
        rose: "var(--color-rose)",
        "rose-light": "var(--color-rose-light)",
        sage: "var(--color-sage)",
        sand: "var(--color-sand)",
        white: "var(--color-white)",
        border: "var(--color-border)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Arial", "sans-serif"],
        display: ["var(--font-playfair)", "Georgia", "serif"],
      },
      fontSize: {
        10: ["var(--text-10)", { lineHeight: "var(--leading-10)" }],
        11: ["var(--text-11)", { lineHeight: "var(--leading-11)" }],
        12: ["var(--text-12)", { lineHeight: "var(--leading-12)" }],
        13: ["var(--text-13)", { lineHeight: "var(--leading-13)" }],
        14: ["var(--text-14)", { lineHeight: "var(--leading-14)" }],
        15: ["var(--text-15)", { lineHeight: "var(--leading-15)" }],
        16: ["var(--text-16)", { lineHeight: "var(--leading-16)" }],
        17: ["var(--text-17)", { lineHeight: "var(--leading-17)" }],
        19: ["var(--text-19)", { lineHeight: "var(--leading-19)" }],
        20: ["var(--text-20)", { lineHeight: "var(--leading-20)" }],
        21: ["var(--text-21)", { lineHeight: "var(--leading-21)" }],
        22: ["var(--text-22)", { lineHeight: "var(--leading-22)" }],
        23: ["var(--text-23)", { lineHeight: "var(--leading-23)" }],
        24: ["var(--text-24)", { lineHeight: "var(--leading-24)" }],
        25: ["var(--text-25)", { lineHeight: "var(--leading-25)" }],
        28: ["var(--text-28)", { lineHeight: "var(--leading-28)" }],
        32: ["var(--text-32)", { lineHeight: "var(--leading-32)" }],
        34: ["var(--text-34)", { lineHeight: "var(--leading-34)" }],
        36: ["var(--text-36)", { lineHeight: "var(--leading-36)" }],
        42: ["var(--text-42)", { lineHeight: "var(--leading-42)" }],
        44: ["var(--text-44)", { lineHeight: "var(--leading-44)" }],
        46: ["var(--text-46)", { lineHeight: "var(--leading-46)" }],
        52: ["var(--text-52)", { lineHeight: "var(--leading-52)" }],
        58: ["var(--text-58)", { lineHeight: "var(--leading-58)" }],
        72: ["var(--text-72)", { lineHeight: "var(--leading-72)" }],
        hero: ["var(--text-hero)", { lineHeight: "var(--leading-hero)" }],
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        9: "var(--space-9)",
        10: "var(--space-10)",
        11: "var(--space-11)",
        12: "var(--space-12)",
        13: "var(--space-13)",
        14: "var(--space-14)",
        16: "var(--space-16)",
        20: "var(--space-20)",
        24: "var(--space-24)",
        28: "var(--space-28)",
        32: "var(--space-32)",
        36: "var(--space-36)",
        40: "var(--space-40)",
        44: "var(--space-44)",
        48: "var(--space-48)",
        52: "var(--space-52)",
        56: "var(--space-56)",
        60: "var(--space-60)",
        64: "var(--space-64)",
        72: "var(--space-72)",
        80: "var(--space-80)",
        96: "var(--space-96)",
        page: "var(--space-page)",
        section: "var(--space-section)",
        "hero-top": "var(--space-hero-top)",
        "hero-bottom": "var(--space-hero-bottom)",
        "card-pad": "var(--space-card-pad)",
        "button-x": "var(--space-button-x)",
        "grid-gap": "var(--space-grid-gap)",
      },
      maxWidth: {
        content: "var(--layout-content)",
      },
      borderRadius: {
        card: "var(--radius-card)",
        panel: "var(--radius-panel)",
        image: "var(--radius-image)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        card: "0 12px 32px rgb(53 22 27 / 8%)",
        float: "0 20px 60px rgb(53 22 27 / 16%)",
      },
      aspectRatio: {
        hero: "1.09",
        project: "1.87",
        "project-compact": "2.38",
      },
    },
  },
  plugins: [],
};

export default config;
